services:
  db:
    image: postgres:16
    container_name: hubic_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hubic
    ports:
            - "5433:5432"

    volumes:
      - hubic_pgdata:/var/lib/postgresql/data

volumes:
  hubic_pgdata:
